services:
  zb-weather-diary:
    image: zb-weather-diary
    container_name: zb-weather-diary
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10001:10001"
    depends_on:
      - mysql
    env_file:
      - .env
    networks:
      - backend

  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql-data: